import type { ContextItem } from "./types.ts";

const now = "2026-05-04T00:00:00.000Z";
const sourceFile = "/Users/amar/Downloads/instructions.md";

export function createBootstrapItems(): ContextItem[] {
  return [
    {
      id: "ctx_bootstrap_area_kernel_mission",
      namespace: "project_facts",
      type: "bootstrap_instruction",
      title: "AREA Context Kernel is the agent infrastructure priority",
      body: "AREA needs a persistent Context Kernel, queryable Context Store, AREA MCP Server, lifecycle hooks, and AREA-specific skills so Codex, Claude Code, and ChatGPT can retrieve and refresh shared project context.",
      summary:
        "Build shared AREA agent context infrastructure: Context Store, MCP tools, hooks, and skills for Codex, Claude Code, and ChatGPT.",
      tags: ["area", "context-kernel", "agent-infrastructure"],
      sourceType: "external_doc",
      sourceRef: "AREA Codex Instructions 2026-05-04 sections 1 and 5",
      sourceUrlOrFile: sourceFile,
      confidence: 0.95,
      status: "accepted",
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      supersedesId: null,
      version: 1,
      embedding: null,
      metadata: { bootstrap: true },
    },
    {
      id: "ctx_bootstrap_smallest_slice",
      namespace: "current_state",
      type: "bootstrap_instruction",
      title: "Build the smallest reliable Context Kernel slice first",
      body: "The first reliable slice is the Context Store schema, context.healthcheck, context.get_project_brief, context.search, context.fetch, Codex SessionStart hook, and one area-context-kernel skill.",
      summary:
        "Initial implementation should prioritize schema, core read tools, SessionStart hook, and the area-context-kernel skill.",
      tags: ["area", "bootstrap", "implementation-order"],
      sourceType: "external_doc",
      sourceRef: "AREA Codex Instructions 2026-05-04 section 16",
      sourceUrlOrFile: sourceFile,
      confidence: 0.95,
      status: "accepted",
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      supersedesId: null,
      version: 1,
      embedding: null,
      metadata: { bootstrap: true },
    },
    {
      id: "ctx_bootstrap_store_contract",
      namespace: "architecture_decisions",
      type: "bootstrap_contract",
      title: "Context items must be structured and source referenced",
      body: "Context items need namespace, type, title, body, summary, tags, source information, confidence, status, timestamps, supersession/version fields, optional embedding, and metadata. Canonical facts should preserve previous versions instead of being overwritten.",
      summary:
        "Context records are structured, auditable, source-referenced, and version-aware.",
      tags: ["area", "context-store", "schema"],
      sourceType: "external_doc",
      sourceRef: "AREA Codex Instructions 2026-05-04 sections 5.3 and 5.4",
      sourceUrlOrFile: sourceFile,
      confidence: 0.95,
      status: "accepted",
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      supersedesId: null,
      version: 1,
      embedding: null,
      metadata: { bootstrap: true },
    },
    {
      id: "ctx_bootstrap_area_product",
      namespace: "project_facts",
      type: "bootstrap_fact",
      title: "AREA ist ein Automated Real-Estate Analyst",
      body: "AREA analysiert Immobilien-Exposés automatisch. Nutzer geben eine Exposé-URL ein, AREA extrahiert Daten, prüft Qualität, und generiert einen strukturierten Analyse-Report mit Ampelsystem (Rot/Amber/Teal). Das System nutzt GPT-4.1 über n8n-Webhooks für die Analyse und bietet PDF-Export und Demo-Modus.",
      summary:
        "AREA analysiert Immobilien-Exposés per URL, erzeugt strukturierte Reports mit Ampelsystem, nutzt GPT-4.1 via n8n und bietet PDF-Export sowie Demo-Modus.",
      tags: ["area", "product", "core"],
      sourceType: "file",
      sourceRef: "AREA repository README and existing codebase",
      sourceUrlOrFile: null,
      confidence: 0.95,
      status: "accepted",
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      supersedesId: null,
      version: 1,
      embedding: null,
      metadata: { bootstrap: true },
    },
    {
      id: "ctx_bootstrap_area_stack",
      namespace: "architecture_decisions",
      type: "bootstrap_fact",
      title: "AREA Tech Stack",
      body: "Frontend: React + Vite + TypeScript + Tailwind + shadcn/ui. Backend: Express + tRPC + Drizzle ORM + PostgreSQL (Railway). Analyse-Pipeline: n8n Webhooks -> GPT-4.1. Hosting: Railway. Context Kernel: Custom MCP Server (TypeScript, stdio + HTTP) mit JSONL local store und Postgres-Pfad.",
      summary:
        "AREA nutzt React/Vite/TypeScript im Frontend, Express/tRPC/Drizzle/PostgreSQL im Backend, n8n/GPT-4.1 für Analysen und einen TypeScript-MCP Context Kernel.",
      tags: ["area", "stack", "architecture"],
      sourceType: "file",
      sourceRef: "AREA repository package.json and server structure",
      sourceUrlOrFile: null,
      confidence: 0.95,
      status: "accepted",
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      supersedesId: null,
      version: 1,
      embedding: null,
      metadata: { bootstrap: true },
    },
    {
      id: "ctx_bootstrap_area_phase",
      namespace: "current_state",
      type: "bootstrap_fact",
      title: "AREA ist in Phase 2 — Auth + Dashboard",
      body: "Phase 1 (Manus-Entkopplung, Standalone) ist abgeschlossen. Phase 2 umfasst Magic-Link/Auth, User Dashboard und Analyse-History; diese Bereiche sind im aktuellen Repository bereits angelegt. Der Context Kernel wird parallel als Agent-Infrastruktur ausgebaut.",
      summary:
        "AREA hat Phase 1 abgeschlossen; Phase 2 umfasst Auth, Dashboard und Analyse-History, während der Context Kernel parallel ausgebaut wird.",
      tags: ["area", "phase", "current-state", "active-task"],
      sourceType: "file",
      sourceRef: "AREA project planning and repository session history",
      sourceUrlOrFile: null,
      confidence: 0.9,
      status: "accepted",
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      supersedesId: null,
      version: 1,
      embedding: null,
      metadata: { bootstrap: true },
    },
    {
      id: "ctx_bootstrap_area_repo_structure",
      namespace: "code_index",
      type: "bootstrap_fact",
      title: "AREA Repository Hauptstruktur",
      body: "server/_core/index.ts ist der Express-Einstiegspunkt. server/routers/ enthält tRPC-Router. client/ ist die React-Vite-App. mcp/area-context-server/ ist der Context Kernel MCP Server. .codex/ enthält Codex-Konfiguration und Hooks. context-store/ enthält Migrationen und lokale JSONL-Daten. Die App nutzt Drizzle ORM mit PostgreSQL auf Railway.",
      summary:
        "AREA besteht aus Express/tRPC unter server/, React/Vite unter client/, Context Kernel unter mcp/area-context-server, Codex-Hooks unter .codex und Context-Store-Dateien unter context-store.",
      tags: ["area", "repo", "structure", "code-index"],
      sourceType: "file",
      sourceRef: "AREA repository file structure inspection",
      sourceUrlOrFile: null,
      confidence: 0.9,
      status: "accepted",
      createdAt: now,
      updatedAt: now,
      expiresAt: null,
      supersedesId: null,
      version: 1,
      embedding: null,
      metadata: { bootstrap: true },
    },
  ];
}
